{
 "title": "Host Resource Usage",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{job=\"node-exporter\",instance=\"localhost:9100\",node!=\"idle\"}[1m]))\n",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "MemoryUsage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\",instance=\"localhost:9100\"} - node_memory_MemFree_bytes{job=\"node-exporter\",instance=\"localhost:9100\"} - node_memory_Cached_bytes{job=\"node-exporter\",instance=\"localhost:9100\"} - node_memory_Buffers_bytes{job=\"node-exporter\",instance=\"localhost:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\",instance=\"localhost:9100\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node-exporter\",instance=\"localhost:9100\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\",instance=\"localhost:9100\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"node-exporter\",instance=\"localhost:9100\",device!~\"/dev/loop.*\",device!~\"tmpfs | nsfs\", device!~\"gvfsd-fuse.*\"} - node_filesystem_avail_bytes{job=\"node-exporter\",instance=\"localhost:9100\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"node-exporter\",instance=\"localhost:9100\",device!~\"/dev/loop.*\",device!~\"tmpfs | nsfs\",device!=\"gvfsd_fuse\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node-exporter\",instance=\"localhost:9100\"}[5m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node-exporter\",instance=\"localhost:9100\"}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  }
 ]
}