---
#If we combine a when statement with a loop, Ansible processes the condition separately for each item.
- name: conditional statements
  hosts: dev
  tasks:
    - name: Run with items greater than 5
      shell: "echo {{ item }}"
      loop: [ 0, 2,4,6,8,10 ]
      when: item > 5
